format = "$time$directory$git_branch$git_state$git_status$cmd_duration$line_break$character"

add_newline = true
scan_timeout = 30

[time]
disabled = false
style = "bold bright-green"
format = '[\[ $time \]]($style) '
time_format = '%T'

[directory]
truncation_length = 5
truncation_symbol = "…/"
truncate_to_repo = true
use_os_path_sep = false # 在 Windows 下也是 "/" 作为分隔符
read_only = " "

# 普通的路径
style = "bold blue underline"
format = """\
[$path]($style)\
[$read_only]($read_only_style)\
[ ](none)\
"""

# git 仓库的路径
repo_root_style = "bold bright-blue underline"
repo_root_format = """\
[$repo_root]($repo_root_style)\
[$path]($style)\
[$read_only]($read_only_style)\
[ ](none)\
"""

[git_branch]
format = "[$symbol$branch]($style)[ ](none)"
symbol = ""
style = "bold purple"

[git_state]
format = "[$state](none)[ ](none)"
merge = "[MERGING](yellow bold)"

[git_status]
style = "dimmed bold purple"
ignore_submodules = true

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[character]
error_symbol = "[»](bold bright-red)"
success_symbol = "[»](bold bright-cyan)"
